spring:
  application:
    name: auth
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:}
      credentials:
        location: ${GCP_CREDENTIALS_PATH:}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth}
    username: ${DB_USERNAME:auth_username}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 10
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s

  mail:
    test-connection: false
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    debug: false

auth:
  issuer-uri: ${AUTH_ISSUER_URI:}
  cookie:
    secure: ${AUTH_COOKIE_SECURE:true}
  verification:
    base-url: ${AUTH_VERIFICATION_BASE_URL:}
    rate-limit-max: ${EMAIL_VERIFICATION_RATE_LIMIT:3}
  login-attempt:
    max-attempts: ${LOGIN_MAX_ATTEMPTS:5}
    lock-duration-minutes: ${LOGIN_LOCK_DURATION_MINUTES:15}
  oauth2:
    client-id: ${OAUTH2_CLIENT_ID:client-app}
    client-secret: ${OAUTH2_CLIENT_SECRET:}
    redirect-uri: ${OAUTH2_REDIRECT_URI:}

server:
  port: ${SERVER_PORT:8081}

security:
  jwt:
    issuer: ecommerce-auth
    access-token-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:900}
    refresh-token-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:2592000}
    secret: ${JWT_SECRET:}
